### ISSUE TITLE
False positive on WeChat built-in browser

### ISSUE THREAD

**Issue by tvvocold** [fingerprintjs/BotD#101]
Testing site: https://fingerprintjs.github.io/BotD/main/
System: iOS 16.1.1 
App: [Wechat](https://apps.apple.com/us/app/%E5%BE%AE%E4%BF%A1/id414478124) 8.0.30
Log: https://pastebin.com/raw/iwp2A6kR
Testing step: Open a friend dialogue in App, send [the testing site link](https://fingerprintjs.github.io/BotD/main/) and open it

**Comment by tvvocold** [comment]
Also false positive on [Wecom](https://apps.apple.com/us/app/%E4%BC%81%E4%B8%9A%E5%BE%AE%E4%BF%A1/id1087897068) build-in browser:
log: https://pastebin.com/6tVFqgqq

**Comment by xnerhu** [comment]
Please, check for false positive using our dev playground. https://fingerprintjs.github.io/BotD/dev/

**Comment by tvvocold** [comment]
> Please, check for false positive using our dev playground. https://fingerprintjs.github.io/BotD/dev/ 

Looks good now, well done👍
