### ISSUE TITLE
False positive on Baidu, Quark and UC browser

### ISSUE THREAD

**Issue by tvvocold** [fingerprintjs/BotD#102]
System: iOS 16.1.1
Testing site: https://fingerprintjs.github.io/BotD/main/

1. False positive on [Baidu App](https://apps.apple.com/us/app/%E7%99%BE%E5%BA%A6/id382201985)
Log: https://pastebin.com/raw/2e5RZSch

2. False positive on [Quark browser](https://apps.apple.com/us/app/%E5%A4%B8%E5%85%8B-%E6%96%B0%E7%94%9F%E4%BB%A3%E6%99%BA%E8%83%BD%E6%90%9C%E7%B4%A2/id1160172628)
Log: https://pastebin.com/raw/MHJYshzJ

3. Also False postitive on [UC browser](https://apps.apple.com/us/app/uc%E6%B5%8F%E8%A7%88%E5%99%A8-%E5%A4%B4%E6%9D%A1%E6%8A%A2%E5%85%88%E7%9C%8B/id586871187)
Log: https://pastebin.com/raw/iHRZy16G

**Comment by xnerhu** [comment]
Please, check for false positive using our dev playground. https://fingerprintjs.github.io/BotD/dev/

**Comment by tvvocold** [comment]
> Please, check for false positive using our dev playground. https://fingerprintjs.github.io/BotD/dev/

Bug fixed, nice job, thx

**Comment by tvvocold** [comment]
@xnerhu 
thx, BTW when will this commit merge to the main branch?

**Comment by xnerhu** [comment]
> @xnerhu thx, BTW when will this commit merge to the main branch?

Soon. Need to do some other tests :)
