### ISSUE TITLE
Abnormal IP database obtained from big data analysis

### ISSUE THREAD

**Issue by tvvocold** [fingerprintjs/BotD#107]
Since most crawlers send requests from specific IPs such as data centers, you can use your BotD's ( cloud version ) big data to analyze recent abnormal IPs and open source the IP database, like this project: https://github.com/antoinevastel/avastel-bot-ips-lists

**Comment by xnerhu** [comment]
Thank you for your suggestion. We actually had the same idea and we work on it for BotD Pro. We don't have any plans to work on it on BotD OSS tho right now.

**Comment by xnerhu** [comment]
Closing for now. If you have any questions, feel free to reach out.
