### ISSUE TITLE
headed playwright chrome with --disable-blink-features=AutomationControlled not detected

### ISSUE THREAD

**Issue by Le0Developer** [fingerprintjs/BotD#112]
Headed chromium is only detected by `navigator.webdriver`, which can be disabled with the `--disable-blink-features=AutomationControlled` launch option.

Technically this also applies to Webkit, as there only navigator.webdriver is detected too, but I haven't found a launch option to do that yet. (It can still be done with stealth scripts but those are easier to detect)

Reproduction code:

```py
from playwright.sync_api import sync_playwright, TimeoutError


with sync_playwright() as p:
    print("Testing chromium")
    # disable headless & navigator.webdriver
    browser = p.chromium.launch(headless=False, args=["--disable-blink-features=AutomationControlled"])
    page = browser.new_page()
    page.goto('https://fingerprintjs.github.io/BotD/main/')
    try:
        handle = page.wait_for_selector("#result.result-detected", timeout=1_000)
    except TimeoutError:
        print("Chromium is undetected.")
    else:
        print("Chromium is detected.")
    
    # input("press enter to continue> ")  # just incase you want to see the site yk
    browser.close()

```

**Comment by xnerhu** [comment]
Hi @Le0Developer.

You are right, that detecting webdriver can be bypassed using flags. We won't fix it though, because it's not the scope of BotD OSS. If you want more sophisticated bot detection, see our BotD Pro https://fingerprint.com/products/bot-detection/

I'm closing for now, if you have any other questions, lmk.
