### ISSUE TITLE
Bot detection fail

### ISSUE THREAD

**Issue by zortext** [fingerprintjs/BotD#154]
1) Goto https://pikwy.com/ 
2) Enter https://fingerprint.com/products/bot-detection/ as url
3) Output fails to detect bot.
![image](https://github.com/fingerprintjs/BotD/assets/23383362/be119922-b1a6-4ebc-913a-6dbc4cc03327)

**Comment by Romchela** [comment]
Thanks, we will take a look!

**Comment by xnerhu** [comment]
We investigated this issue in the context of BotD Pro. Closing since we haven't found any way to detect it yet.
