### ISSUE TITLE
Googlebot Desktop: BotD detection fail 

### ISSUE THREAD

**Issue by dinhduc2402** [fingerprintjs/BotD#155]
Testing BotD: Googlebot Desktop in Chrome.
Output {bot: false}
See image below:
![botd-issue](https://github.com/fingerprintjs/BotD/assets/33125202/b9d1176d-731a-4e4b-9f27-19b5234ef229)

**Comment by xnerhu** [comment]
Hi @dinhduc2402. We decided internally to not proceed with implementing crawler-like bots (e.g. google/facebook ect) in BotD OSS.

However, if you care about such functionality, you can check our pro version at https://fingerprint.com/
