### ISSUE TITLE
Ruffle extension caused false positives

### ISSUE THREAD

**Issue by lihe07** [fingerprintjs/BotD#166]
Environment: Firefox 124.0 on Linux.

When [Ruffle extension](https://addons.mozilla.org/en-US/firefox/addon/ruffle_rs/) is installed, it will replace `navigator.plugins` and `navigator.mimeTypes`, resulting in false positives of two related tests.

![console](https://github.com/fingerprintjs/BotD/assets/53819558/8ac7b6b9-ae49-4339-97a6-9a509e7bb285)

**Comment by xnerhu** [comment]
Hi. Thanks for the issue. Ruffle modifies those values resulting in detecting it as "spoofed".

**Comment by lihe07** [comment]
I am not sure about the best practice to resolve this. I currently applied a workaround targeting specifically the Ruffle extension.
