### ISSUE TITLE
/results endpoint does not accept requests id in the cookie

### ISSUE THREAD

**Issue by makma** [fingerprintjs/botd#17]
According to my knowledge about the repo, the `/results` endpoint should accept the request id parameter in both forms - `id` query string parameter and cookie. Querying with query string parameter works just fine, however, I was not able to receive the correct response using the cookie. I tried various cookie names: `botId`, `botd-id`, `botd-request-id`, `botdId`, `id`.
## Steps to reproduce:
1. Send request
```
GET https://botd.fpapi.io/api/v1/results
Headers: 
Auth-Token: <token>
Content-Type: application/json
Cookie: botId=01F9VRKJJCNDWPRRXMGED6T1K0; botd-id=01F9VRKJJCNDWPRRXMGED6T1K0; botd-request-id=01F9VRKJJCNDWPRRXMGED6T1K0; botdId=01F9VRKJJCNDWPRRXMGED6T1K0; id=01F9VRKJJCNDWPRRXMGED6T1K0
```

**Received response:** `{"error":{"code":"Failed","message":"'id' parameter is not passed"}}`

**Expected response:**
```{"status":"processed","bot":{"automationTool":{"status":"processed","probability":0},"browserSpoofing":{"status":"processed","probability":0},"searchEngine":{"status":"processed","probability":0}},"vm":{"status":"processed","probability":0},"ip":"193.165.236.186","requestId":"01F9VQCY00YBW3DYJXAVQVEK9F"}```

**Comment by Romchela** [comment]
We don't expect passing request id through cookie (only query string param). But if it's more clear we can do it.

**Comment by Romchela** [comment]
Done
