### ISSUE TITLE
CORS policy issue when trying to import the script from openfpcdn.io/botd/v1 using Firefox

### ISSUE THREAD

**Issue by Woorooo** [fingerprintjs/BotD#172]
I'm encountering a CORS policy issue in Firefox when trying to import the script from https://openfpcdn.io/botd/v1. The error message in the console is: 

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://openfpcdn.io/botd/v1. (Reason: CORS request did not succeed). Status code: (null).

**Comment by makma** [comment]
Hello @Woorooo  our CDN sets correct ACA* headers. From my experience, browsers just hide different problems behind the Same Origin Policy issues, likely the script (CDN URL) is blocked on the browser side by adblocker (try to check in the incognito mode).

If you believe this is not the case, please provide steps to reproduce and publicly accessible page where we can investigate the mentioned behavior.

Thank you.
Martin

**Comment by Woorooo** [comment]
I used Firefox 128.0.3 64bit on Windows, incognito mode, all extensions disabled and I get this error. 

Example page: https://www.felicidance.com/

The same also happens on mobile Firefox on Android. 
All other browsers I've tested don't have this problem. 

Let me know if you need anything else, thank you.

**Comment by makma** [comment]
Oh, I see, sadly, Firefox does not like us, and our CDN is blocked in this browser with the default settings. To avoid this, you can use the npm package (I believe it contains all the necessary code and does not request the CDN) or copy the served script from the CDN into your codebase (sadly, you'd need to update manually in the future for newer versions).

**Comment by Woorooo** [comment]
I will server the script locally, it should be good for now. Thank you.
