### ISSUE TITLE
Tag object is not returned by getResult

### ISSUE THREAD

**Issue by makma** [fingerprintjs/botd#18]
When using `tag` object as a `detect()` function's parameter I expect receiving `tag` information from `getResult()` function but there is no `tag` in the response.

## Steps to reproduce
1. Use botd's `detect()` function with `tag` parameter
```js
    const botdPromise = Botd.load({
      token: 'RBKN12LFJAyyjMSr30J',
      mode: 'allData',
    })
    const botd = await botdPromise
    const botdDetectResult = await botd.detect({myMetadata1: "ahoj", myMetadata2: "hello"})
```
**Received response**
```json
{
  "status": "processed",
  "bot": {
    "automationTool": {
      "status": "processed",
      "probability": 0
    },
    "browserSpoofing": {
      "status": "processed",
      "probability": 0
    },
    "searchEngine": {
      "status": "processed",
      "probability": 0
    }
  },
  "vm": {
    "status": "processed",
    "probability": 0
  },
  "ip": "193.165.236.186",
  "requestId": "01F9X4ER48RTQZ9K0RYC8BFC7J"
}
```
**Expected response**
Same response with the `tag` object included

## Reproduced on
**Code:** https://github.com/makma/martinmakarsky.com/blob/experiment-page/src/templates/not-very-secret-experiment-page.jsx#L28
**Deployed site:** https://deploy-preview-10--martinmakarsky-preview-delivery-api.netlify.app/not-very-secret-experiment-page

**Comment by Romchela** [comment]
Done
