### ISSUE TITLE
Thinks Firefox Ubuntu is Playwright with Probability 1

### ISSUE THREAD

**Issue by ThomasAitken** [fingerprintjs/BotD#28]
After receiving a token, I immediately tested the cdn version of your library on a toy app (in debug mode, hosted on localhost on my computer). I'm using Ubuntu 20.04. On my Chromium browser, the result was expected: three 0 probability results for each of the bot scenarios ("automationTool", "browserSpoofing", "searchEngine"). But on my Firefox browser, the result was the same except for the probability=1 conclusion that I was using Playwright.
`automationTool: Object { status: "processed", probability: 1, type: "playwright" }`

This was using a normal browser window - not incognito - using an unadulterated installation of Firefox, with user agent "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0". This user agent has not been altered.

What's the story here?

**Comment by Romchela** [comment]
Could you provide requestId, please?

**Comment by ThomasAitken** [comment]
01FDVQE4X78GSPBQFSKCEEKCE7

**Comment by Romchela** [comment]
Did you do this request with an open developer console?

**Comment by ThomasAitken** [comment]
Yes

**Comment by Romchela** [comment]
Thank you for the issue, we will fix it soon

**Comment by r-valitov** [comment]
Fixed
