### ISSUE TITLE
Improve server API docs

### ISSUE THREAD

**Issue by Valve** [fingerprintjs/BotD#40]
1. Explain why we need to call the server API in one sentence (it's a server-to-server, secure way of getting the botd results back).
2. Get rid of the the POST /detect section entirely (but copy the response format to GET /results), because users will not be using that.
3. Explain that you need to detect client-side first, get requestID and then get results with `GET /results` on the server second, passing the requestID
4. Make the server API docs read like a book from top to bottom so that a developer is able to quickly solve their server use case w/out having to jump in the document (make most important information to be at the top, not at the bottom).
/cc @makma

**Comment by tvvocold** [comment]
btw the server api docs need to update, I found that the new parameter `verifyCounter: 1` is very confusing, what does it mean?

**Comment by tvvocold** [comment]
and in order to avoid false positives, what range of `probability` scores can I consider the client to be a human? for example, less than 0.2?

**Comment by Romchela** [comment]
@tvvocold thanks for your suggestions. I've added this information to [Server API docs](https://github.com/fingerprintjs/BotD/blob/main/docs/server_api.md).
