### ISSUE TITLE
Different results in the same browser on different websites

### ISSUE THREAD

**Issue by bentzibentz** [fingerprintjs/BotD#57]
We have installed BotD on one of our pages as a test. We always get as result a probability of 0.8 for automationTool and status "puppeteer". The result is the same at different browsers and also at different computers.

But if we visit with the same browsers and same machines your test page https://fingerprintjs.com/products/bot-detection/ we always get the result "You are not a bot".

What could be the reasons for the different results? Our test site is an angular v13 spa build als dev version.

I am looking forward to a solution idea.

**Comment by bentzibentz** [comment]
01FZD4FNH6K52YPEYTJ6VZ7B9Z

**Comment by Romchela** [comment]
@bentzibentz could you check it now?

**Comment by bentzibentz** [comment]
@Romchela it seems to work now

```
automationTool: {status: "processed", probability: 0}
browserSpoofing: {status: "processed", probability: 0}
searchEngine: {status: "processed", probability: 0}
```

**Comment by emiliorcueto** [comment]
Is there an answer to what the solution was here?   We have implemented BotD as well and are experiencing false positives, particularly with Brave browser.  However, using the same browsers on your test page is successful with "You are not a bot".  Any clarity you can provide would be extremely helpful as a considerable amount of our community prefers Brave

**Comment by bentzibentz** [comment]
Unfortunately we have the same error again. It seems that the adjustments made at that time are no longer effective.

**Comment by xnerhu** [comment]
@bentzibentz Please go to https://fingerprintjs.github.io/BotD/ and paste all of the logs here.

**Comment by xnerhu** [comment]
Closing since this issue is related to BotD Pro and BotD OSS works locally now. If you have any issues, do not hesitate to ask :)
