### ISSUE TITLE
server API  very slow

### ISSUE THREAD

**Issue by Nooobita** [fingerprintjs/BotD#60]
It takes almost a second, please add cdn

**Comment by Nooobita** [comment]
china

**Comment by Romchela** [comment]
Currently we have servers only in US. After release in August it's possible that we'll have more locations.

**Comment by yitd** [comment]
> 目前我们只有在美国有服务器。在八月发布之后，我们可能会有更多的地点。

It is recommended to use cloudflare cdn

**Comment by hckhanh** [comment]
I hope it will have a server in Singapore or Hongkong (Asia)

**Comment by Romchela** [comment]
@hckhanh we will have India Mumbai region soon

**Comment by Nooobita** [comment]
will the CDN be added?

**Comment by tvvocold** [comment]
same issue here, plz consider providing a private server build version (We can pay for it); or add more cdn (fastly.com is pretty good since GitHub is using it too, or cloudflare.com) for the better verification speed. @Romchela
