### ISSUE TITLE
Fully open source BotD

### ISSUE THREAD

**Issue by Romchela** [fingerprintjs/BotD#65]
We want to make our BotD fully open source library which is working on the client side. 
Several things to do:
1) Architecture of the project (understand how to add detection logic to existing open source client)
2) Implement auto tool detectors

Looks like we don't want to publish anything except automation tool detectors because of multiple reasons:
1) How to do a reverse DNS lookup on the client side if we want to check search bots? How should we cache the results? 
2) Browser spoofing: we can add it without any problems, but first, we need to discuss & design "tampering detection".
3) VM: we can add it as well, but the current logic is not stable and maybe it's better to postpone it/do it on further iterations.

**Comment by xnerhu** [comment]
Hi @tvvocold! We are still working on the release, which will launch soon.

**Comment by adriaanvanrossum** [comment]
I see https://github.com/fingerprintjs/BotD/releases/tag/v1.0.0-beta.1 is released. Does this mean we can use the bot detection without an API key / backend request?

**Comment by xnerhu** [comment]
@tvvocold @adriaanvanrossum in case you have missed it, we released full version `1.0.0`.
