### ISSUE TITLE
BotD is blocked by Easylist

### ISSUE THREAD

**Issue by zoontek** [fingerprintjs/BotD#66]
Hi 👋
Since a few days, we notice BotD domain is blocked by Easylist: https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_trackingservers.txt#L78

<img width="588" alt="Screenshot 2022-09-02 at 10 38 06" src="https://user-images.githubusercontent.com/1902323/188099925-3980feec-37f3-4ae0-b5f5-88fd4a5e8db3.png">

Is it because BotD script is served on the same domain as Fingerprint? Because BotD is not a tracker.
Would it be possible to use a different domain / a custom domain (this setting is available for Fingerprint in the dashboard)? We had to fallback on captcha, it makes user experience horrible 😕

**Comment by Romchela** [comment]
Hi @zoontek,
We are going to make BotD fully open source project without backend (see https://github.com/fingerprintjs/BotD/issues/65), ETA of the first version 1 month.
It should aggregate all basic bot detection techniques. So, we don't support old BotD version right now.

Also, we will have PRO version that includes advanced detectors and you will be able to activate it in our Dashboard. In this case you can use subdomain integration to be safe from any blocking.

**Comment by zoontek** [comment]
Hi @Romchela,

I saw that after opening the issue, asked the support to activate BotD product on our account.
I also has a quick question: since the verify counter seems to have be removed from the API response, how to be sure that a requestID is not re-used multiple time? Do we have to setup a cache on our side to perform a similar check?

**Comment by Romchela** [comment]
> I also have a quick question: since the verify counter seems to have be removed from the API response, how to be sure that a requestID is not re-used multiple time? Do we have to setup a cache on our side to perform a similar check?

Checking timestamp of the request is actually enough.
