### ISSUE TITLE
False positive - navigator.conection.rtt

### ISSUE THREAD

**Issue by lynt-smitka** [fingerprintjs/BotD#69]
I'm trying beta and have issues with navigator.connection.rtt == 0. I have fast internet, and my real rtt is around 12ms. According to the docs https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/rtt, the rtt is rounded to the nearest 25ms = 0. The result is I'm detected as headless_chrome.

**Comment by xnerhu** [comment]
@lynt-smitka As we changed quite a few things, this issue may not be valid anymore. 
Please check our [playground page](https://fingerprintjs.github.io/BotD/) and if you would get false positive, send the logs here.

**Comment by xnerhu** [comment]
Closing since #98 disables RTT.
