### ISSUE TITLE
Investigate and fix false positives

### ISSUE THREAD

**Issue by xnerhu** [fingerprintjs/BotD#83]
Refs:
- android web browsers (WeChat etc.) https://github.com/fingerprintjs/BotD/commit/980a9fe6d28b601d6e4b3443b9190196e211ba16#commitcomment-85162176
- rtt connection (https://github.com/fingerprintjs/BotD/pull/67#discussion_r981300985)

TODO:
- [x] #93 
- [x] Test for regressions
- [x] Test Samsung Browser
- [x] Test Android Webview

**Comment by LKNSI** [comment]
https://phantom.app/ is setting off false alarms, given that the text search is looking for `phantom` explicitly.

Phantom uses `window.phantom`. I'm not immediately sure about how you can make a distinction, but it's something that's being flagged right now.

**Comment by 10maurycy10** [comment]
It also flags ungoogled-chromium as a bot.

**Comment by xnerhu** [comment]
Ref #90

**Comment by xnerhu** [comment]
> It also flags ungoogled-chromium as a bot.

I can't replicate this. Would you send me logs from our [playground page](https://fingerprintjs.github.io/BotD/)? 

I tested on the latest versions for both Win64 and MacOS ARM

**Comment by xnerhu** [comment]
Closing. @10maurycy10 if you have any more false positives, please create another issue.
